### ISSUE TITLE
Pagination with future enabled gives errors

### ISSUE THREAD

**Issue by Raytray** [sverrirs/jekyll-paginate-v2#12] opened 2017-02-10 22:24 UTC
I'm not entirely sure if this is accurate. But my situation is that the pagination with debug information indicated it processed the future page but failed to finish when building..

```
±bundle exec jekyll build --drafts
Configuration file: /home/raytray/Development/raysite/_config.yml
            Source: /home/raytray/Development/raysite
       Destination: /home/raytray/Development/raysite/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
         AutoPages: Disabled/Not configured in site.config.
        Pagination: ----------------------------
        Pagination: Page: blog/index.html
        Pagination:  Active configuration
        Pagination:   Enabled:          true
        Pagination:   Items per page:   5
        Pagination:   Permalink:        /page/:num/
        Pagination:   Title:            :title - page :num
        Pagination:   Limit:            0
        Pagination:   Sort by:          date
        Pagination:   Sort reverse:     true
        Pagination:  Active Filters
        Pagination:   Collection:       posts
        Pagination:   Category:         [Not set]
        Pagination:   Tag:              [Not set]
        Pagination:   Locale:           [Not set]
        Pagination:  Filtering by: Category   42 => 42
        Pagination:  Filtering by: Tag        42 => 42
        Pagination:  Filtering by: Locale     42 => 42
jekyll 3.4.0 | Error:  comparison of Jekyll::Document with Jekyll::Document failed
```

With future turned on, even with no future posts to build this error occurred.
With future turned off, with both future and no future posts, this error did not appear.

**Comment by sverrirs** [comment] 2017-02-10 22:27
Hi Raymond, thanks for reporting this issue. Could you run the command again with the `- - trace` switch added and paste the extra stack trace info in here. 

`jekyll build --drafts --trace`

**Comment by Raytray** [comment] 2017-02-11 03:17
```
±bundle exec jekyll build --drafts --trace
Configuration file: /home/raytray/Development/raysite/_config.yml
            Source: /home/raytray/Development/raysite
       Destination: /home/raytray/Development/raysite/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
         AutoPages: Disabled/Not configured in site.config.
        Pagination: ----------------------------
        Pagination: Page: blog/index.html
        Pagination:  Active configuration
        Pagination:   Enabled:          true
        Pagination:   Items per page:   5
        Pagination:   Permalink:        /page/:num/
        Pagination:   Title:            :title - page :num
        Pagination:   Limit:            0
        Pagination:   Sort by:          date
        Pagination:   Sort reverse:     true
        Pagination:  Active Filters
        Pagination:   Collection:       posts
        Pagination:   Category:         [Not set]
        Pagination:   Tag:              [Not set]
        Pagination:   Locale:           [Not set]
        Pagination:  Filtering by: Category   42 => 42
        Pagination:  Filtering by: Tag        42 => 42
        Pagination:  Filtering by: Locale     42 => 42
/home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-paginate-v2-1.7.3/lib/jekyll-paginate-v2/generator/paginationModel.rb:221:in `sort!': comparison of Jekyll::Document with Jekyll::Document failed (ArgumentError)
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-paginate-v2-1.7.3/lib/jekyll-paginate-v2/generator/paginationModel.rb:221:in `paginate'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-paginate-v2-1.7.3/lib/jekyll-paginate-v2/generator/paginationModel.rb:67:in `block in run'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-paginate-v2-1.7.3/lib/jekyll-paginate-v2/generator/paginationModel.rb:34:in `each'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-paginate-v2-1.7.3/lib/jekyll-paginate-v2/generator/paginationModel.rb:34:in `run'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-paginate-v2-1.7.3/lib/jekyll-paginate-v2/generator/paginationGenerator.rb:129:in `generate'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:174:in `block in generate'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:172:in `each'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:172:in `generate'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/lib/jekyll/site.rb:68:in `process'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/lib/jekyll/command.rb:26:in `process_site'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:63:in `build'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:34:in `process'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/raytray/.rvm/gems/ruby-2.3.0/gems/jekyll-3.4.0/exe/jekyll:13:in `<top (required)>'
	from /home/raytray/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `load'
	from /home/raytray/.rvm/gems/ruby-2.3.0/bin/jekyll:23:in `<main>'
	from /home/raytray/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/raytray/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Here you go, thanks for looking into this!

**Comment by sverrirs** [comment] 2017-02-11 18:05
@Raytray Hi Raymond, I've unfortunately been unable to reproduce this issue you describe for draft posts. 

_What I did:_
* Added a post dated in the future to the `example 02` project
* Built the project using the `jekyll build --drafts" command.

Could you please share with me the front matter of one of the draft posts that is causing this exception and any other configuration that you might consider relevant.

Also could you please try to reproduce this error using one of the example projects under `/examples/`.  https://github.com/sverrirs/jekyll-paginate-v2/tree/master/examples/02-category gives a reasonable representation of a medium complexity pagination project.

**Comment by Raytray** [comment] 2017-02-12 21:03
I was able to reproduce it here: https://github.com/Raytray/jekyll-paginate-v2/tree/issue-12

I set future in the config to be true and added a few draft posts as well as a small folder structure within the drafts folder. Not sure if that's expected/allowed.

**Comment by sverrirs** [comment] 2017-02-13 07:27
Thank you for taking the time to debug this further. Yes I agree, the problem is somewhere in the sorting of the posts. I will have a look as soon as I can.

**Comment by sverrirs** [comment] 2017-02-21 09:54
Hi Raymond, I just wanted you to know I haven't forgotten about you or this issue. Just been a bit busy with life stuff. I will get to this as soon as I can :)

**Comment by Ovilia** [comment] 2017-02-24 05:38
I met with the same problem. Waiting... 😞

**Comment by sverrirs** [comment] 2017-03-03 21:36
OK so an update on this issue. 
It seems as though this is a problem in the bowels of Jekyll. I've started a discussion with the Jekyll Core team about this.  https://github.com/jekyll/jekyll/issues/5931

However I'm going to submit a semi-permanent fix for this issue as I don't want to wait for the Jekyll team's decision.

**Closed** 2017-03-03 21:44 UTC
Labels: possible bug

**Comment by sverrirs** [comment] 2017-03-03 21:46
Please check out [gem v1.7.4](https://rubygems.org/gems/jekyll-paginate-v2/versions/1.7.4) for the fix.
