### ISSUE TITLE
Get rid of `index.html` in previous_page_path and next_page_path

### ISSUE THREAD

**Issue by alvarotrigo** [sverrirs/jekyll-paginate-v2#49] opened 2017-11-02 15:58 UTC
I would like to have links to my pages without the index.html.
Right now `previous_page_path` and `next_page_path` add `index.html` at the end. For example:

> http://localhost:4000/page/2/index.html

I would like to have:

> http://localhost:4000/pepe/2/

I'm currently making use of this code for the pagination links I found on the typical blog example:

```html 

  <!--
    Showing buttons to move to the next and to the previous list of posts (pager buttons).
  -->
  {% if paginator.total_pages > 1 %}
  <ul class="pager">
      {% if paginator.previous_page %}
      <li class="previous">
          <a href="{{ paginator.previous_page_path | prepend: site.baseurl | replace: '//', '/' }}">&larr; Newer Posts</a>
      </li>
      {% endif %}
      {% if paginator.next_page %}
      <li class="next">
          <a href="{{ paginator.next_page_path | prepend: site.baseurl | replace: '//', '/' }}">Older Posts &rarr;</a>
      </li>
      {% endif %}
  </ul>
  {% endif %}
```

**Comment by alvarotrigo** [comment] 2017-11-21 15:48
At the moment I'm replacing `index.html` for ``:

```html
href="{{ paginator.next_page_path | prepend: site.baseurl | replace: '//', '/' |  replace: 'index.html', '' }}"
```

**Comment by sverrirs** [comment] 2017-11-28 22:25
Hi sorry about the long no-reply to this issue.
This is actually a duplicate of an already tracked issue #41 . Let's move the discussion there and I'll close this ticket if that is OK?

**Closed by sverrirs** 2017-11-28 22:25 UTC

**Comment by alvarotrigo** [comment] 2017-11-29 00:29
Sure. Thanks for pointing it out!

**Comment by sverrirs** [comment] 2018-01-11 22:33
Fixed in gem https://rubygems.org/gems/jekyll-paginate-v2/versions/1.9.2

**Comment by alvarotrigo** [comment] 2018-01-11 22:42
Awesome! Thanks!
