### ISSUE TITLE
Sort posts by alternative date results in error

### ISSUE THREAD

**Issue by MattGreyDesign** [sverrirs/jekyll-paginate-v2#43] opened 2017-10-11 22:23 UTC
Hi, I'm building a music blog with paginated pages that lists albums by album release date instead of blog post date, the only problem is I get an error when trying to sort by any frontmatter date that isn't it's built-in `date:`. All other `sort_field` values work fine.

for example

The file named
`2017-05-05-bibio_fix-this-thang.md`

Has the Frontmatter
```
---
published: true
release_date: 2015-05-05
---
```

When in the `config.yml` I set the sort to `sort_field: 'release_date'` I get this error in the console:

```
jekyll 3.5.2 | Error:  comparison of Jekyll::Document with Jekyll::Document failed
```

**Comment by sverrirs** [comment] 2017-10-12 05:56
Which version of the paginate-v2 gem are you using?

**Comment by sverrirs** [comment] 2017-10-12 13:10
I will have to take a look at this better as it sounds like it might be a regression bug for an older issue. Give me a few days to find time to investigate. :)

**Comment by MattGreyDesign** [comment] 2017-10-12 18:58
I think I found the problem, some of the posts had a timestamp as well as the date, when I removed them (eg `2015-05-05 16:16:01`). Not sure if this is expected behaviour or a bug.

**Comment by sverrirs** [comment] 2017-10-13 08:23
Ah, great thanks for updating me on this issue. If removing the timestamp solved the ettor then this is most definitely a bug as I had intended for time to be supported as well. I will have a look and fix :)

**Comment by ibrado** [comment] 2017-11-30 16:56
Hi! It looks like the comparison fails when comparing a Time and Date...

```
a.inspect=2017-11-29 23:41:16 +0800
a.class=Time

b.inspect=#<Date: 2017-11-30 ((2458088j,0s,0n),+0s,2299161j)>
b.class=Date
```

**Comment by ibrado** [comment] 2017-12-10 12:38
Hi @MattGreyDesign ... Does the fix work for you?

**Comment by ibrado** [comment] 2017-12-22 12:01
@sverrirs Maybe this should be closed now..?

**Comment by MattGreyDesign** [comment] 2017-12-22 13:24
@ibrado I will test it when I can

**Comment by MattGreyDesign** [comment] 2018-01-15 15:35
Apologies for the late follow-up... Christmas and New Year and whatnot! ☃️ . I tried this out again with this frontmatter`published_date: 2017-11-29 16:16:01` and still seem to get the same error (works fine without `16:16:01`).

```Generating...
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
  Liquid Exception: Liquid error (line 5): comparison of Jekyll::Document with Jekyll::Document failed in /_layouts/author.html
jekyll 3.5.2 | Error:  Liquid error (line 5): comparison of Jekyll::Document with Jekyll::Document failed
```

Said template it is throwing up an error for:

```---
layout: default
---
<h3>Author</h3>
<h1>{{ page.name }}</h1>

{% assign this_author = page.slug %}
{% assign tracks = site.posts | where: "author", this_author | sort: 'published_date'%}

<ul>
{% for track in tracks %}
  <li><a href="/tracks/{{ track.slug }}">{{ track.title }}</a></li>
{% endfor %}
</ul>
```

I updated through bundler and it's definitely using `jekyll-paginate-v2 (1.9.2)`

**Comment by ibrado** [comment] 2018-01-15 17:15
Ah, wait. I thought you were using the paginate-v2 sort_field, not the Liquid sort filter?

**Comment by MattGreyDesign** [comment] 2018-01-17 13:56
Sorry I pasted the wrong bit of code, but I've realised that it is actually a Jekyll error with the sorting that Paginate also inherits, I will make an issue over on the Jekyll repo. Thanks for your help!

**Comment by sverrirs** [comment] 2018-01-17 13:58
Thanks for the update Matt, I will close this ticket then :)

**Closed by sverrirs** 2018-01-17 13:58 UTC
Labels: bug, help wanted
